export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const CHANGE_CURRENCY = "CHANGE_CURRENCY";
export const CHANGE_COUNTRY = "CHANGE_COUNTRY";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREMENT_CART_ITEM = "INCREMENT_CART_ITEM";
export const DECREMENT_CART_ITEM = "DECREMENT_CART_ITEM";